// Client-side export helpers: markdown reports, CSV tables, JSON history.

export function downloadBlob(filename, content, mime = "text/plain") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function csvCell(value) {
  if (value === null || value === undefined) return "";
  const text = String(value);
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export function tableToCsv(table) {
  if (!table || table.type !== "table") return "";
  const lines = [table.columns.map(csvCell).join(",")];
  for (const row of table.rows) {
    lines.push(table.columns.map((c) => csvCell(row[c])).join(","));
  }
  return lines.join("\n");
}

function slugify(text) {
  return (
    String(text)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "analysis"
  );
}

export function reportToMarkdown(run) {
  const lines = [];
  lines.push(`# Analysis Report`);
  lines.push("");
  lines.push(`- **Dataset:** ${run.datasetName || "unknown"}`);
  lines.push(`- **Date:** ${new Date(run.date).toLocaleString()}`);
  lines.push(`- **Question:** ${run.question}`);
  lines.push("");
  lines.push(`## Answer`);
  lines.push("");
  lines.push(run.answer || "(no answer text)");
  lines.push("");

  const table = run.result;
  if (table && table.type === "table" && table.rows?.length) {
    lines.push(`## Result table (${table.row_count ?? table.rows.length} rows)`);
    lines.push("");
    lines.push(`| ${table.columns.join(" | ")} |`);
    lines.push(`| ${table.columns.map(() => "---").join(" | ")} |`);
    for (const row of table.rows) {
      lines.push(
        `| ${table.columns.map((c) => csvCell(row[c]).replace(/\|/g, "\\|") || "—").join(" | ")} |`
      );
    }
    lines.push("");
  } else if (table && table.type === "value") {
    lines.push(`## Result`);
    lines.push("");
    lines.push(`**${table.value}**`);
    lines.push("");
  }

  if (run.code) {
    lines.push(`## Generated pandas code`);
    lines.push("");
    lines.push("```python");
    lines.push(run.code);
    lines.push("```");
  }

  lines.push("");
  lines.push(`_Generated by AnalystOS · local AI data analyst_`);
  return lines.join("\n");
}

export function exportRunReport(run) {
  downloadBlob(
    `analystos-report-${slugify(run.question)}.md`,
    reportToMarkdown(run),
    "text/markdown"
  );
}

export function exportRunCsv(run) {
  const csv = tableToCsv(run.result);
  if (!csv) return false;
  downloadBlob(`analystos-table-${slugify(run.question)}.csv`, csv, "text/csv");
  return true;
}

export function exportHistoryJson(items) {
  downloadBlob(
    "analystos-history.json",
    JSON.stringify(items, null, 2),
    "application/json"
  );
}
